/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailensalazar.laberintoproyecto.vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Usuario
 */
public class GUILaberinto extends javax.swing.JFrame {

    /**
     * Creates new form GUILaberinto
     */
    public GUILaberinto() {
        initComponents();

    }

    public PanelJuego getPanelJuego(){
    
        return panelJuego;
    
    }
    
    public void escuchar (ActionListener controlador){
    
    
        btnMenu.addActionListener(controlador);
        
    }
    
    public void escucharMouse(MouseListener controlador){
    
        this.addMouseListener(controlador);
    
    }
    
    public void escucharTeclado (KeyListener controlador){
    
        this.addKeyListener(controlador);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        panelJuego = new ailensalazar.laberintoproyecto.vista.PanelJuego();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonMenu.png"))); // NOI18N
        btnMenu.setActionCommand("menu");
        btnMenu.setContentAreaFilled(false);
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 140, 73));

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private ailensalazar.laberintoproyecto.vista.PanelJuego panelJuego;
    // End of variables declaration//GEN-END:variables
}
