/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailensalazar.laberintoproyecto.vista;

import ailensalazar.laberintoproyecto.controlador.ControladorPrincipal;

/**
 *
 * @author Usuario
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    
    public void escuchar (ControladorPrincipal controlador){
    
        btnInstrucciones.addActionListener(controlador);
        btnJugar.addActionListener(controlador);
        btnHistoria.addActionListener(controlador);
        btnSalir.addActionListener(controlador);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historia.png"))); // NOI18N
        btnHistoria.setActionCommand("historia");
        btnHistoria.setContentAreaFilled(false);
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 260, 80));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonsalir.png"))); // NOI18N
        btnSalir.setActionCommand("salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 250, 70));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugar.png"))); // NOI18N
        btnJugar.setActionCommand("jugar");
        btnJugar.setContentAreaFilled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 250, 80));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btninstrucciones.png"))); // NOI18N
        btnInstrucciones.setActionCommand("instrucciones");
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 310, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
