/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ailensalazar.laberintoproyecto.vista;

import ailensalazar.laberintoproyecto.controlador.ControladorLaberinto;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class PanelJuego extends javax.swing.JPanel {
    
    private ImageIcon fondo;
    private ControladorLaberinto controlador;

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        fondo= new ImageIcon("./src/main/resources/img/laberinto proyecto solo.png");
    }

    public void setControlador(ControladorLaberinto controlador){
        this.controlador = controlador;
    
    }
    
    public void paint(Graphics g){
        super.paint(g);
        fondo.paintIcon(null, g, 0, 0);
        if (controlador!=null){
            controlador.dibujar(g);
        //    g.drawString("Hola",100,100);
        }
    }

    public ImageIcon getLaberintoGrafico() {
        return fondo;
    }

    public ControladorLaberinto getControlador() {
        return controlador;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laberinto proyecto solo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
